### ISSUE TITLE
Need some help about connection.

### ISSUE THREAD

**Issue by wixa** [IoTBits/ESP32_SGTL5000_driver#1]
In audiobit.h i find numbers of GPIO where i must connect to my ESP32. But i have 3 question:
1. What is "#define AUDIOBIT_BCK			26" - on your board have no BCK pin?
2. Where i must connect MCLK pin "#define AUDIOBIT_MCLK			0" or i must not connect it?
3. Why in main.c 
"audiobit_play();
 xTaskCreate(i2c_test_task, "i2c_test_task_1", 1024 * 2, (void* ) 1, 10, NULL);" 
is commented? it is dont work yet?

**Comment by iot-bits** [comment]
1. The BCK or SCLK are the bit clock pins for I2S. The I2S standard is not properly standardized and different manufacturers call the pins by different names.
2. You must connect MCLK to GPIO0 only. The ESP32 can output MCLK to very few pads, GPIO0 being one of those.
3. The task was for testing I2C bus.Everything in the driver works now.
It will play the audio file at 48kHz stereo when you make this driver and upload to ESP32.
